#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -u

if [ $(id -u) -ne 0 ]; then
  printf "Script must be run as root. Try 'sudo ./rakpios-cli-install'\n"
  exit 1
fi


DIR="/bin/.rakpios-cli"

if [ -d "$DIR" ]; then
  echo "looks like rakpios-cli is already installed in "$DIR"..."
  exit 1
else
  mkdir -p /bin/.rakpios-cli/bin
  curl https://raw.githubusercontent.com/Sheng2216/cli-test/main/bin/rakpios-cli-udp -o /bin/.rakpios-cli/bin/rakpios-cli-udp
  curl https://raw.githubusercontent.com/Sheng2216/cli-test/main/bin/rakpios-cli-network -o /bin/.rakpios-cli/bin/rakpios-cli-network
  chmod +x /bin/.rakpios-cli/bin/rakpios-cli*
fi

echo "export PATH=$DIR/bin:$PATH">>~/.bashrc

source ~/.bashrc

echo "install success"
