#!/bin/bash

# set -o errexit
# set -o nounset
# set -o pipefail
# set -u
set -e

# the script needs privileged access to run
if [ $(id -u) -ne 0 ]; then
    printf "Script must be run as root. Try 'sudo ./rakpios-cli-install'\n"
    exit 1
fi

# usage information
usage() {
    cat 1>&2 <<EOF
rakpios-cli-install 0.0.1 (hash 2022-10-10)
The installer for rakpios-cli
USAGE:
    rakpios-cli-install [FLAGS]
FLAGS:
    -i, --install           Install rakpios-cli
    -u, --upgrade           Upgrade rakpios-cli
    -h, --help              Prints help information
EOF
}

DIR="/bin/.rakpios-cli"

main(){
    SHORT=i,u,h
    LONG=install,upgrade,help
    OPTS=$(getopt --options $SHORT --longoptions $LONG -- "$@")

    if [ $? -ne 0 ]; then
        usage
        exit 0
    fi
    
    eval set -- "$OPTS"
    
    while :
    do
        case $1 in
            -h | --help) # display Usage information
                usage
                exit 0
                ;;
            -i | --install) # Install rakpios-cli
                do_check_install_status
                exit 0
                ;;
            -u | --upgrade) # Upgrade rakpios-cli
                do_upgrade
                exit 0
                ;;
            *)
                echo "invalid command: $1"
                usage
                exit 0
                ;;
        esac
    done

}

do_check_install_status(){
    if [ -d "$DIR" ]; then
        whiptail --title "Confirmation" --yesno "Looks like rakpios-cli is already installed in "$DIR" \nDo you want to upgrade the rakpios-cli to the latest version?" 10 78 --yes-button "Yes" --no-button "No" 
        if [[ $? -eq 0 ]]; then 
            do_upgrade
        elif [[ $? -eq 1 ]]; then 
            exit 0
        fi    
    else
        do_fresh_install
        # echo "rakpios-cli successfully installed!"
        whiptail --msgbox "rakpios-cli successfully upgraded!" 10 60
        exit 0
    fi 
}

do_print_install_location(){
    echo "The rakpios-cli will be installed in the ${DIR}"
}

do_upgrade(){
    # remove the directory
    rm -rf $DIR
    # deleate the configuration saved in the bashrc
    awk '!/rakpios-cli/' ~/.bashrc > tmpfile && mv tmpfile ~/.bashrc
    # install the latest rakpios-cli
    do_fresh_install
    whiptail --msgbox "rakpios-cli successfully updated to the latest version!" 10 60
    exit 0
}

do_fresh_install(){
    # print install location
    do_print_install_location
    mkdir $DIR
    
    # download the portainer app template and Stack file from portainer-template repo
    curl https://github.com/RAKWireless/portainer-templates/archive/refs/heads/master.zip -L -o $DIR/files.zip && unzip -o $DIR/files.zip -d $DIR/
    cp $DIR/portainer-templates-master/portainer_app_template.json $DIR
    cp -r $DIR/portainer-templates-master/Stack/ $DIR
    rm -rf $DIR/files.zip $DIR/portainer-templates-master/
    
    echo "done"
    # download the scripts from the rakpios-cli repo 
    curl https://github.com/Sheng2216/cli-test/archive/refs/heads/main.zip -L -o $DIR/rakpios-cli-bin.zip && unzip -o $DIR/rakpios-cli-bin.zip -d $DIR/
    cp -r $DIR/cli-test-main/bin $DIR/bin
    cp $DIR/cli-test-main/rakpios-cli $DIR/
    rm -rf $DIR/rakpios-cli-bin.zip $DIR/cli-test-main
    # add the rakpios-cli diretory to the PATH
    echo "export PATH=$DIR/bin:$PATH">>~/.bashrc
    source ~/.bashrc
}

main "$@" || exit 1
