#!/bin/bash

env_full_list="PUID="1000" -e PGID="100" -e TZ="Europe/London" -e MODEL=null -e CONCENTRATOR=null -e INTERFACE="SPI" -e HAS_GPS="1" -e HAS_LTE="0" -e RESET_GPIO="17" -e POWER_EN_GPIO="0" -e RADIO_DEV=null -e GPS_DEV=null -e GATEWAY_EUI_NIC="eth0" -e GATEWAY_EUI=null -e TTN_REGION="eu1" -e SERVER_HOST=null -e SERVER_PORT="1700" -e BAND="eu_863_870" -e GPS_LATITUDE=null -e GPS_LONGITUDE=null -e GPS_ALTITUDE=null"
echo "env_full_list is ${env_full_list}"
env_name_to_configure=GPS_ALTITUDE
value_changed_to_text=RAK7246
new_env_pair=`echo "${env_name_to_configure}=${value_changed_to_text}"`
echo "new env pair: ${new_env_pair}"

modified_env_full_list=$(echo ${env_full_list} | sed "s/${env_name_to_configure}*\S*/${new_env_pair}/g")
#modified_env_full_list=$(echo ${env_full_list} | sed "s/\S*/${new_env_pair}/g")
echo "modified env full list is ${modified_env_full_list}"
